[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y python3 python3-pip ffmpeg"
]

[install]
cmds = ["pip3 install --break-system-packages -r requirements.txt"]

[start]
cmd = "python3 app.py"